version: "3.8"
services:
  gps-decoder:
    image: node:14-alpine
    volumes:
      - .:/app
    command: sh -c "node --version && npm --version && cd /app && npm i && node device_alarm.js"
    ports:
      - "3000:3002"
      - "1339:1339"

  alert-decoder:
    image: node:14-alpine
    volumes:
      - .:/app
    command: sh -c "node --version && npm --version && cd /app && npm i && node server.js"
    ports:
      - "3005:3005"